invoice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("login", Login.as_view(), name="login"),
    path("extract", Extract.as_view(), name="extract"),
    #path("download", Download.as_view(), name="download"),
    path("upload", Upload.as_view(), name="upload"),
    path("logout", Logout.as_view(), name="logout"),
]

main/models.py
from django.db import models

main/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth import authenticate
from django.shortcuts import render
from django.conf import settings
from django  import forms
from django.views import View
from beyond.settings import BASE_DIR
from .models import *
from . import extract
import os

class upload(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput())

class Login(View):
    def get(self, request):
        if 'user_id' in request.session:
            return HttpResponseRedirect('/')
        
        return render(request, 'main/login.html', {
        })

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email.split('@')[0], password=password)
        if user is not None:
            request.session['user_id'] = user.id
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('login')

class Index(View):
    def get(self, request):
        if 'user_id' not in request.session:
            return HttpResponseRedirect('login')
        form = upload()
        return render(request, 'main/index.html', {'form':form})

class Extract(View):
    def get(self, request):
        if 'user_id' not in request.session:
            return HttpResponseRedirect('login')
        extract.extract_all_pdfs(str(BASE_DIR) + '/main/static/main/input',str(BASE_DIR) + '/main/static/main/output')

        file_path = str(BASE_DIR) + '/main/static/main/output/Report3.xlsx'
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                return response
        raise Http404
        
        form = upload()
        return render(request, 'main/index.html', {'form':form})
####
    #class Download(View):
     #def get(self, request):
        #file_path = str(BASE_DIR) + '/main/static/main/output/Report3.xlsx'
        #if os.path.exists(file_path):
           # with open(file_path, 'rb') as fh:
                 #response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                 #response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                 #return response
            #raise Http404

class Upload(View):
    def post(self, request):
        form = upload(request.POST,request.FILES)
        if form.is_valid():
            for f in request.FILES.getlist('file'):
                self.handle_uploaded_file(f)
            return render(request,'main/success.html',{})
        else:
            form = upload()
            return render(request,'main/index.html',{'form':form})

    def get(self, request):
        form = upload()
        return render(request,'main/index.html',{'form':form})

    def handle_uploaded_file(self,f):
        #with open(str(BASE_DIR) + '/main/static/main/input/' + f.name,'wb+') as destination:
            
            #for chunk in f.chunks():
                
                #destination.write(chunk)
        file_path = str(BASE_DIR) + '/main/static/main/input/' + f.name
        print('File Path:', file_path)  # Add this line
        with open(file_path, 'wb+') as destination:
            for chunk in f.chunks():
             destination.write(chunk)

class Logout(View):
    def get(self, request):
        try:
            del request.session['user_id']
            return HttpResponseRedirect('login')
        except KeyError as e:
            return HttpResponseRedirect('/')

main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    
    <title>Extract Data</title>
</head>

<body>
    <div class="body">
        <div class="mainSection">
            <div class="sideBar secA">
            </div>
            <div class="loginContent secB">
                <h1>Mail Extraction</h1>
                <a href="#">Select Email</a>
                <a href="#">Download Data</a>
                <a href="#">Select Folder</a>
            </div>
            <div class="loginContent secC">
                <h1>Invoice Extraction</h1>
                <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Extract Details</button>
                <a href="{% url 'main:extract'%}">Generated Output</a>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Upload Files</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'main:upload'%}" method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    {{form.as_p}}
                    <button type="submit">Upload</button>
                </form>
            </div>
        </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

main/templates/main/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>Login</title>
</head>

<body>
    <div class="body">
        <div class="mainSection">
            <div class="sideBar">
            </div>
            <div class="loginContent">
                <h1>Login to your Account</h1>
                <form action="{% url 'main:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="email">EMAIL</label>
                        <input type="email" name="email" id="email">
                    </div>
                    <div class="fieldWrapper">
                        <label for="password">PASSWORD</label>
                        <input type="password" name="password" id="password">
                    </div>
                    <input type="submit" value="Sign In">
                </form>
                <button>Continue with Google</button>
                <p>Don't have an account? <a href="#">Sign Up</a></p>
            </div>
        </div>
    </div>
</body>

</html>

main/templates/main/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    
    <title>Extract Data</title>
</head>

<body>
    <div class="body">
        <div class="mainSection success">
            <div class="sideBar secA">
            </div>
            
            <div class="loginContent secC">
                <h1>Files Uploaded Successfully</h1>
                
                <a href="{% url 'main:index'%}"> <i class="fa fa-hand-o-left"></i> Back to Main Menu</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>